set_property IOSTANDARD LVCMOS33 [get_ports {ones2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ones2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ones2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ones2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_ones[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_ones[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_ones[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_ones[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_ones[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_ones[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_ones[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_tens[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_tens[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_tens[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_tens[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_tens[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_tens[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_tens[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tens2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tens2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tens2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tens2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tens1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tens1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tens1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tens1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ones1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ones1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ones1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ones1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports bright_ones]
set_property IOSTANDARD LVCMOS33 [get_ports LED]
set_property IOSTANDARD LVCMOS33 [get_ports bright_tens]

set_property PACKAGE_PIN P5 [get_ports {tens1[0]}]
set_property PACKAGE_PIN P4 [get_ports {tens1[1]}]
set_property PACKAGE_PIN P3 [get_ports {tens1[2]}]
set_property PACKAGE_PIN P2 [get_ports {tens1[3]}]

set_property PACKAGE_PIN R2 [get_ports {ones1[0]}]
set_property PACKAGE_PIN M4 [get_ports {ones1[1]}]
set_property PACKAGE_PIN N4 [get_ports {ones1[2]}]
set_property PACKAGE_PIN R1 [get_ports {ones1[3]}]

set_property PACKAGE_PIN U3 [get_ports {tens2[0]}]
set_property PACKAGE_PIN U2 [get_ports {tens2[1]}]
set_property PACKAGE_PIN V2 [get_ports {tens2[2]}]
set_property PACKAGE_PIN V5 [get_ports {tens2[3]}]

set_property PACKAGE_PIN V4 [get_ports {ones2[0]}]
set_property PACKAGE_PIN R3 [get_ports {ones2[1]}]
set_property PACKAGE_PIN T3 [get_ports {ones2[2]}]
set_property PACKAGE_PIN T5 [get_ports {ones2[3]}]

set_property PACKAGE_PIN D2 [get_ports {seven_ones[0]}]
set_property PACKAGE_PIN E2 [get_ports {seven_ones[1]}]
set_property PACKAGE_PIN F3 [get_ports {seven_ones[2]}]
set_property PACKAGE_PIN F4 [get_ports {seven_ones[3]}]
set_property PACKAGE_PIN D3 [get_ports {seven_ones[4]}]
set_property PACKAGE_PIN E3 [get_ports {seven_ones[5]}]
set_property PACKAGE_PIN D4 [get_ports {seven_ones[6]}]

set_property PACKAGE_PIN B2 [get_ports {seven_tens[0]}]
set_property PACKAGE_PIN B3 [get_ports {seven_tens[1]}]
set_property PACKAGE_PIN A1 [get_ports {seven_tens[2]}]
set_property PACKAGE_PIN B1 [get_ports {seven_tens[3]}]
set_property PACKAGE_PIN A3 [get_ports {seven_tens[4]}]
set_property PACKAGE_PIN A4 [get_ports {seven_tens[5]}]
set_property PACKAGE_PIN B4 [get_ports {seven_tens[6]}]

set_property PACKAGE_PIN G1 [get_ports bright_ones]
set_property PACKAGE_PIN H1 [get_ports bright_tens]
set_property PACKAGE_PIN K2 [get_ports LED]

